### PR TITLE
Create 404.html

### PR DESCRIPTION
**Pull request by Kundan28**

### CODE REVIEW

**Comment by blizz-aurifex** [comment]
Hey @Kundan28, what's the motivation behind this PR?

**Comment by Kundan28** [comment]
@blizz-aurifex We can make a page for 404 error. Now it's simple but later it can be made attractive.

**Comment by blizz-aurifex** [comment]
I guess what I meant to ask is what benefit does adding a 404 page provide? http://blizzard.github.com/d3-api-docs/ just redirects to our development portal. Additionally, if you do go to an invalid page on that site GitHub will still serve their default 404.

**Comment by Kundan28** [comment]
But we can make that page more attractive by ourself.

**Pull request closed without merging**
